_wandb:
    value:
        cli_version: 0.25.0
        e:
            sbskr4jjrf3po56rigmp9wtidwj52zvt:
                codePath: c:\Users\JAYDEEP\Python_Project\DA IITM\DA6401\A1\da6401_assignment_1\notebooks\wandb_report.ipynb
                codePathLocal: wandb_report.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "487147433984"
                        used: "356064919552"
                email: jaydeepmakwana316@gmail.com
                executable: c:\Users\JAYDEEP\Python_Project\DA IITM\DA6401\A1\da6401_assignment_1\.venv\Scripts\python.exe
                host: jaydeep
                memory:
                    total: "7966765056"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\JAYDEEP\Python_Project\DA IITM\DA6401\A1\da6401_assignment_1\notebooks\wandb_report.ipynb
                python: CPython 3.13.12
                root: c:\Users\JAYDEEP\Python_Project\DA IITM\DA6401\A1\da6401_assignment_1\notebooks
                startedAt: "2026-02-28T14:48:52.006419Z"
                writerId: sbskr4jjrf3po56rigmp9wtidwj52zvt
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.13.12
            "5": 0.25.0
            "8":
                - 1
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 128
hidden_size_val:
    value: 64
learning_rate:
    value: 0.0001
loss:
    value: mse
num_layers:
    value: 3
optimizer:
    value: rmsprop
weight_decay:
    value: 0
weight_init:
    value: xavier
