wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size_val:
  value: 64
learning_rate:
  value: 0.005
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: xavier
